services:
  smart-proxy:
    build:
      context: .
      dockerfile: dockerfile
    container_name: smart-proxy
    ports:
      - "9091:9091"
    volumes:
      - ./data:/app/data
    restart: unless-stopped